DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD(
	BOARD_NO NUMBER NOT NULL,
	USERS VARCHAR2(100 BYTE) NOT NULL,
	BOARD_TITLE VARCHAR2(100 BYTE) NOT NULL,
	CONTENT     VARCHAR2(400 BYTE),
	BOARD_DAY DATE,	
	CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'신준호', '제목입니다', '내용이지',SYSDATE);
COMMIT;