DROP TABLE PROCEEDING;
DROP TABLE EMPLOYEE;
DROP TABLE PJT;
DROP TABLE PROCEEDING;



CREATE TABLE DEPARTMENT(
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL, -- PK
    DEPT_NAME VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL
);

CREATE TABLE PJT(
    PJT_NO NUMBER NOT NULL,  -- PK
    PJT_NAME VARCHAR2(30 BYTE) NULL,
    BEGIN_DATE DATE NULL,
    END_DATE DATE NULL
);




CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER NOT NULL, -- PK
    ERPT_NO VARCHAR2(15 BYTE) NULL, -- FK
    POSITION CHAR(10 BYTE) NULL, 
    NAME VARCHAR2(15 BYTE) NULL,
    HIRE_DATE DATE NULL,
    SALARY NUMBER NULL
);




/*  프로젝트 진행 테이블 생성 */
CREATE TABLE PROCEEDING(
    PCD_NO NUMBER NOT NULL,  -- PK
    EMP_NO NUMBER NULL, --FK
    PJT_NO NUMBER, -- FK
 --   PJT_STATE NUMBER NOT NULL
);


-- 기본키 추가
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO);

ALTER TABLE PJT
    ADD CONSTRAINT PK_PJT PRIMARY KEY(PJT_NO);
    

    
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT PK_EMPLOYEE 
    











    