DROP TABLE STUDENT;
DROP TABLE PROFESSOR;
DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE COURSE;


CREATE TABLE STUDENT(
    S_NO NUMBER NOT NULL,
    S_NAME VARCHAR2(30 BYTE) NULL,
    S_ADDRESS VARCHAR2(100 BYTE) NULL,
    S_GRADE_NO NUMBER(1) NULL,
    P_NO NUMBER NOT NULL
);


CREATE TABLE PROFESSOR(
    P_NO NUMBER NOT NULL,
    P_NAME VARCHAR2(30 BYTE) NULL,
    P_MAJOR VARCHAR2(30 BYTE)
);





CREATE TABLE ENROLL(
    E_NO NUMBER NOT NULL,
    S_NO NUMBER NOT NULL,
    C_NO NUMBER NOT NULL,
    E_DATE DATE NULL
);


CREATE TABLE LECTURE(
    L_NO NUMBER NOT NULL,
    P_NO NUMBER NOT NULL,
    E_NO NUMBER NOT NULL,
    L_NAME VARCHAR2(30 BYTE),
    L_LOCATION VARCHAR2(30 BYTE)
);


CREATE TABLE COURSE(
    C_NO NUMBER NOT NULL,
    C_NAME VARCHAR2(30 BYTE) NULL,
    C_UNIT NUMBER(1)
);
    
    
/*  기본키 영역  */    
ALTER TABLE LECTURE
    ADD CONSTRAINT LECTURE_PK PRIMARY KEY(L_NO);
    
ALTER TABLE ENROLL
    ADD CONSTRAINT ENROLL_PK PRIMARY KEY(E_NO);

ALTER TABLE COURSE
    ADD CONSTRAINT COURSE_PK PRIMARY KEY(C_NO);
    
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PROFESSOR_PK PRIMARY KEY(P_NO);
    
ALTER TABLE STUDENT
    ADD CONSTRAINT STUDENT_PK PRIMARY KEY(S_NO);
/*  기본키 영역  */    
    
    
    
/*   외래키 영역  */

ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY (E_NO)
    REFERENCES ENROLL(E_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(P_NO)
    REFERENCES PROFESSOR(P_NO);
    


ALTER TABLE ENROLL
    ADD CONSTRAINT ENROLL_COURSE_FK FOREIGN KEY(C_NO)
    REFERENCES COURSE(C_NO);    
ALTER TABLE ENROLL
    ADD CONSTRAINT ENROLL_STUDENT_FK FOREIGN KEY(S_NO)
    REFERENCES STUDENT(S_NO);
    
    
    
ALTER TABLE STUDENT
    ADD CONSTRAINT STUDENT_PROFESSOR_FK FOREIGN KEY(P_NO)
    REFERENCES PROFESSOR(P_NO);
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
