DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD(
	BOARD_NO NUMBER NOT NULL,
	TITLE VARCHAR2(100 BYTE) NOT NULL,
	USERS VARCHAR2(50 BYTE)NOT NULL,
	HIT NUMBER,
	TO_DATE VARCHAR(10 BYTE),
	CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)	
);
